x <- seq(0, 1,by=0.001)
png(filename="vk3t11.png")
plot(x, (1-x), main="Uskottavuusfunktio", xlab=expression(paste(theta)), ylab=expression(plain("L(")~theta~plain("; x = 0)")), xlim=c(0,1), ylim=c(0,1), type="line",col="red")
lines(x,(1-x)**2, col="orange")
lines(x,(1-x)**3, col="yellow")
lines(x,(1-x)**4, col="green")
lines(x,(1-x)**10, col="blue")
lines(x,(1-x)**100, col="purple")
dev.off()
x <- seq(0, 1,by=0.001)
png(filename="vk3t12.png")
plot(x, (x), main="Uskottavuusfunktio", xlab=expression(paste(theta)), ylab=expression(plain("L(")~theta~plain("; x = n)")), xlim=c(0,1), ylim=c(0,1), type="line",col="red")
lines(x,(x)**2, col="orange")
lines(x,(x)**3, col="yellow")
lines(x,(x)**4, col="green")
lines(x,(x)**10, col="blue")
lines(x,(x)**100, col="purple")
dev.off()